# Generated by Django 3.2.7 on 2021-09-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murmur', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
