# Generated by Django 3.2.7 on 2021-09-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='event_pics'),
        ),
    ]
