# Generated by Django 3.2.5 on 2021-09-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraps', '0002_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='event_pics'),
        ),
    ]
