# Generated by Django 3.2.5 on 2021-09-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='choices',
            field=models.ManyToManyField(to='accounts.CertificationChoices'),
        ),
    ]
