# Generated by Django 3.2.5 on 2021-09-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210913_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CertificationChoices',
            new_name='Certifications',
        ),
        migrations.AlterModelOptions(
            name='certifications',
            options={'verbose_name': '資格', 'verbose_name_plural': '資格群'},
        ),
        migrations.RenameField(
            model_name='certifications',
            old_name='certification',
            new_name='certifications',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='choices',
        ),
        migrations.AddField(
            model_name='profile',
            name='desiredqualification',
            field=models.ManyToManyField(to='accounts.Certifications'),
        ),
    ]
