# Generated by Django 3.2.5 on 2021-09-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210913_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certifications',
            options={'verbose_name': 'certification', 'verbose_name_plural': 'certifications'},
        ),
    ]
