# Generated by Django 3.2.5 on 2021-09-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_certifications_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='get_certified',
            field=models.ManyToManyField(related_name='get_certified', to='accounts.Certifications'),
        ),
    ]
